#version 460
#extension GL_ARB_shading_language_include : require
#extension GL_EXT_nonuniform_qualifier : require
#extension GL_EXT_shader_explicit_arithmetic_types_int64 : require

#include "rt_bindings.glsl"
#include "rt_traversal.glsl" // brings traverse_one_chunk + debug_view_color
#include "rt_debug.glsl"

#define MAX_ITER_COUNT 5000
layout(local_size_x = 8, local_size_y = 8, local_size_z = 1) in;

void main()
{
        uvec2 pixel = uvec2(gl_GlobalInvocationID.xy);
        if (pixel.x >= uint(pc.extent.x) || pixel.y >= uint(pc.extent.y)) return;

        ShaderRayCam cam = G_CAM(pc);
        Ray ray = camera_ray_for_pixel(cam, pixel, pc.extent);
        vec3 hit_pos;
        uint hit_level;
        uint hit_slot;
        uint iter_count;
        uint err_code;
        vec3 hit_color = vec3(0);
        vec3 n_smooth = vec3(0);
        float ao = 0;
        
        int grid_slot = grid_world_to_chunk_index(ray.origin, pc.grid_min_corner, 64, 4);
        GPUGridSlot slot_indices = G_GRID(pc,grid_slot);
        if(slot_indices.nodes_id == UNDEFINED_VALUE)
        {
          vec4 color = vec4(1.0, 1.0, 1.0, 1.0);
          imageStore(G_OUTIMG(pc), ivec2(pixel), color);
        }
        float t_dist = 0;
         bool hit = traverse_one_chunk(
                       slot_indices,
                         ray, vec3(0.0), //   TODO, update later to chunk corner
                        t_dist,
                         hit_pos, hit_level, hit_slot, iter_count, err_code, hit_color, n_smooth, ao);
        
         vec4 color = debug_view_color(
                         pc.debug_mode, hit, iter_count, MAX_ITER_COUNT,
                         hit_level, hit_slot, err_code, hit_color, n_smooth, ao);
        
         imageStore(G_OUTIMG(pc), ivec2(pixel), color);
}
